### ISSUE TITLE
cursed

### ISSUE THREAD

**Issue by ghost** [bottom-software-foundation/bottom-js#2]
this is just cursed...

**Comment by untuned** [comment]
💖💖✨✨,👉👈💖💖,👉👈💖✨✨✨✨🥺,,👉👈💖💖,,,,👉👈✨✨✨✨,,,,👉👈✨✨✨,,👉👈💖💖✨🥺,,,,👉👈💖💖,,,,👉👈💖✨✨✨✨🥺,,👉👈💖💖✨🥺,👉👈✨✨✨,,👉👈💖💖✨✨,👉👈💖💖✨,👉👈💖💖✨🥺,,👉👈✨✨✨,,👉👈💖💖,,,👉👈💖💖✨,👉👈💖💖✨👉👈💖💖✨👉👈💖✨✨✨✨🥺,,👉👈✨✨✨,,👉👈💖💖👉👈💖💖✨,👉👈✨✨✨,,👉👈💖✨✨✨✨🥺,,👉👈💖✨✨✨✨🥺,,,👉👈💖💖✨,👉👈💖💖✨🥺,,👉👈💖💖✨🥺,👉👈✨✨✨,,👉👈💖💖🥺👉👈💖💖✨🥺,👉👈💖✨,,,👉👈
